#
# This file will be included by cmake/share/sources.cmake
#
# cmake/reflect/_Sources.cmake is generated by `mulle-sde reflect`.
# Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
src/NSDictionary+PropertyList.m
src/NSPropertyListSerialization.m
src/NSString+PropertyList.m
src/Parsing/NSArray+PropertyListParsing.m
src/Parsing/NSData+PropertyListParsing.m
src/Parsing/NSDictionary+PropertyListParsing.m
src/Parsing/NSObject+PropertyListParsing.m
src/Parsing/NSString+PropertyListParsing.m
src/Printing/MulleObjCPropertyListPrinting.m
src/Printing/NSArray+PropertyListPrinting.m
src/Printing/NSData+PropertyListPrinting.m
src/Printing/NSDate+PropertyListPrinting.m
src/Printing/NSDictionary+PropertyListPrinting.m
src/Printing/NSNumber+PropertyListPrinting.m
src/Printing/NSString+PropertyListPrinting.m
src/Stream/MulleObjCBufferedInputStream.m
src/Stream/MulleObjCBufferedOutputStream.m
src/Stream/_MulleObjCPropertyListReader.m
src/Stream/MulleObjCStream.m
src/Stream/MulleObjCUTF8StreamReader.m
)

#
# contents selected with patternfile ??-source--stage2-sources
#
set( STAGE2_SOURCES
src/MulleObjCLoader+MulleObjCPlistFoundation.m
)
