#ifndef mulle_objc_plist_foundation_import_h__
#define mulle_objc_plist_foundation_import_h__

/* This is a central include file to keep dependencies out of the library
   Objective-C files. It is usally imported by Objective-C .h files only.
   .m and .aam use import-private.h.
*/

/*
   Get C includes first
 */
#include "include.h"

/* Include the header file automatically generated by c-sourcetree-update.
   Here the prefix is harmless and serves disambiguation. If you have no
   sourcetree, then you don't need it.
 */

#import "_MulleObjCPlistFoundation-import.h"
#ifdef MULLE_OBJC_PLIST_FOUNDATION_BUILD
# define MULLE_OBJC_PLIST_FOUNDATION_GLOBAL    MULLE_C_GLOBAL
#else
# if defined( MULLE_OBJC_PLIST_FOUNDATION_INCLUDE_DYNAMIC) || (defined( MULLE_INCLUDE_DYNAMIC) && ! defined( MULLE_OBJC_PLIST_FOUNDATION_INCLUDE_STATIC))
#  define MULLE_OBJC_PLIST_FOUNDATION_GLOBAL   MULLE_C_EXTERN_GLOBAL
# else
#  define MULLE_OBJC_PLIST_FOUNDATION_GLOBAL   extern
# endif
#endif


/* You can add some more import statements here */

#endif
