      { @selector( MulleObjCLoader), @selector( MulleObjCContainerFoundation) },      // 47a9beb6;MulleObjCLoader;2132102f;MulleObjCContainerFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCStandardFoundation) },      // 47a9beb6;MulleObjCLoader;ed704a42;MulleObjCStandardFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCTimeFoundation) },      // 47a9beb6;MulleObjCLoader;cc20d48b;MulleObjCTimeFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCValueFoundation) },      // 47a9beb6;MulleObjCLoader;535d5103;MulleObjCValueFoundation
      { @selector( MulleObjCBufferedInputStream), MULLE_OBJC_NO_CATEGORYID },      // 0d289418;MulleObjCBufferedInputStream;;
      { @selector( MulleObjCBufferedOutputStream), MULLE_OBJC_NO_CATEGORYID },      // f919266f;MulleObjCBufferedOutputStream;;
      { @selector( MulleObjCInMemoryInputStream), MULLE_OBJC_NO_CATEGORYID },      // c11e0f43;MulleObjCInMemoryInputStream;;
      { @selector( MulleObjCOutputStream), MULLE_OBJC_NO_CATEGORYID },      // 94c18dd3;MulleObjCOutputStream;;
      { @selector( MulleObjCPropertyListPrinting), MULLE_OBJC_NO_CATEGORYID },      // ae35af0f;MulleObjCPropertyListPrinting;;
      { @selector( MulleObjCUTF8StreamReader), MULLE_OBJC_NO_CATEGORYID },      // 1570378d;MulleObjCUTF8StreamReader;;
      { @selector( NSArray), @selector( NSPropertyListParsing) },      // 233490fe;NSArray;060a8c9c;NSPropertyListParsing
      { @selector( NSArray), @selector( PropertyListPrinting) },      // 233490fe;NSArray;91aeee11;PropertyListPrinting
      { @selector( NSData), @selector( NSPropertyListParsing) },      // 8fce7861;NSData;060a8c9c;NSPropertyListParsing
      { @selector( NSData), @selector( PropertyListPrinting) },      // 8fce7861;NSData;91aeee11;PropertyListPrinting
      { @selector( NSDate), @selector( PropertyListPrinting) },      // cfcedd21;NSDate;91aeee11;PropertyListPrinting
      { @selector( NSDictionary), @selector( NSPropertyListParsing) },      // 8b2abcad;NSDictionary;060a8c9c;NSPropertyListParsing
      { @selector( NSDictionary), @selector( PropertyList) },      // 8b2abcad;NSDictionary;827edd0f;PropertyList
      { @selector( NSDictionary), @selector( PropertyListPrinting) },      // 8b2abcad;NSDictionary;91aeee11;PropertyListPrinting
      { @selector( NSMutableData), @selector( MulleObjCOutputStream) },      // 5d7fdc81;NSMutableData;94c18dd3;MulleObjCOutputStream
      { @selector( NSNull), @selector( PropertyListPrinting) },      // f0c42d79;NSNull;91aeee11;PropertyListPrinting
      { @selector( NSNumber), @selector( PropertyListPrinting) },      // 8ba34f39;NSNumber;91aeee11;PropertyListPrinting
      { @selector( NSObject), @selector( NSPropertyListParsing) },      // b3a66256;NSObject;060a8c9c;NSPropertyListParsing
      { @selector( NSPropertyListSerialization), MULLE_OBJC_NO_CATEGORYID },      // 87901b51;NSPropertyListSerialization;;
      { @selector( NSString), @selector( MulleObjCOutputStream) },      // 1994a171;NSString;94c18dd3;MulleObjCOutputStream
      { @selector( NSString), @selector( NSPropertyListParsing) },      // 1994a171;NSString;060a8c9c;NSPropertyListParsing
      { @selector( NSString), @selector( PropertyList) },      // 1994a171;NSString;827edd0f;PropertyList
      { @selector( NSString), @selector( PropertyListPrinting) },      // 1994a171;NSString;91aeee11;PropertyListPrinting
      { @selector( _MulleObjCBoolNumber), @selector( PropertyListPrinting) },      // 263c5445;_MulleObjCBoolNumber;91aeee11;PropertyListPrinting
      { @selector( _MulleObjCDoubleNumber), @selector( PropertyListPrinting) },      // ae25b758;_MulleObjCDoubleNumber;91aeee11;PropertyListPrinting
      { @selector( _MulleObjCLongDoubleNumber), @selector( PropertyListPrinting) },      // 4ec38072;_MulleObjCLongDoubleNumber;91aeee11;PropertyListPrinting
      { @selector( _MulleObjCPropertyListReader), MULLE_OBJC_NO_CATEGORYID },      // a2dc8d79;_MulleObjCPropertyListReader;;
